name = "moeuasaenglishvocab"
main = "worker.js"
compatibility_date = "2026-08-14"

[[d1_databases]]
binding = "DB"
database_name = "moe-uasa-english-progress"
database_id = "cba815f7-980e-40de-88c6-9830dd3d44c3"
